name: Debug Build

on:
  workflow_dispatch:
    inputs:
      debug-build:
        description: 'Trigger debug build'
        default: 'false'

jobs:
  build_debug:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Debug Build
      if: ${{ github.event.inputs.debug-build == 'true' }}
      run: |
        chmod +x ./gradlew
        ./gradlew assembleDebug
