name: Android Debug CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  debug-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Set up JDK for Android builds (assuming JDK 11 is suitable for your project)
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    # Cache Gradle dependencies (optional but recommended for faster builds)
    - name: Cache Gradle dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # Debug build step
    - name: Run Debug Build
      run: |
        chmod +x ./gradlew
        ./gradlew assembleDebug --stacktrace

    # Optional: Run lint to identify potential issues
    - name: Run Lint
      run: |
        ./gradlew lintDebug

    # Upload the APK as an artifact
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
